package gumbo.engine.general.grouper;

public enum GroupingPolicies {
	
	ALLGROUP,
	NONEGROUP,
//	GUARDGROUP,
//	GUARDGUARDEDGROUP,
	COSTGROUP_GUMBO,
	COSTGROUP_IO,
	COSTGROUP_PAPER,
	BESTCOSTGROUP_GUMBO,
	BESTCOSTGROUP_IO,
	BESTCOSTGROUP_PAPER,
	GUARDEDATOMGROUP
	

	// TODO add other grouping policies
	
}
